# Generated by Django 4.1.3 on 2023-02-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='tech',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
