# Generated by Django 4.1.3 on 2023-02-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_portafolio_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='description',
            field=models.TextField(),
        ),
    ]
