# Generated by Django 4.1.3 on 2023-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_portafolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='link',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
