# Generated by Django 4.1.3 on 2023-02-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='category',
        ),
    ]
