# Generated by Django 4.1.3 on 2023-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_portafolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='link',
            field=models.TextField(),
        ),
    ]
