# Generated by Django 4.1.3 on 2023-02-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_portafolio_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='portafolio',
        ),
    ]
