# Generated by Django 4.1.3 on 2023-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_portafolio_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='category',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='categoty',
            field=models.CharField(default='web', max_length=255),
            preserve_default=False,
        ),
    ]
