# Generated by Django 4.1.3 on 2023-02-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_portafolio_category_portafolio_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portafolio',
            old_name='categoty',
            new_name='category',
        ),
    ]
