# Generated by Django 4.1.3 on 2023-02-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_categoty_portafolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='img',
            field=models.ImageField(default=' ', upload_to='project'),
            preserve_default=False,
        ),
    ]
