# Generated by Django 4.1.3 on 2023-02-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_portafolio_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portafolio',
            old_name='img',
            new_name='img_principal',
        ),
    ]
