# Generated by Django 4.1.3 on 2023-02-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_img_portafolio_img_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portafolio',
            old_name='img_principal',
            new_name='img',
        ),
    ]
